### ISSUE TITLE
Cannot construct the IE Graph correctly in the CLIQ-ai2021_demo

### ISSUE THREAD

**Issue by liuchenzhengyi** [graph4ai/graph4nlp_demo#7]
Hi,
I encountered some problem when I tried to build the IE graph using demo code in CLIQ-ai2021_demo classification problem. By implementation, I simply changed the config file that -- graph_name: 'ie'.

The error says 

"ValueError: num_samples should be a positive integer value, but got num_samples=0"

I checked the built graph in data.pt and label.py, only to find they are null. 

Could someone explain why I encountered this error? Thank you!

**Comment by Nicoleqwerty** [comment]
Hi @liuchenzhengyi , in addition to `graph_name`, you must also change `edge_strategy` and `merge_strategy` in the config file. More details about these parameters are introduced in [IE_doc](https://graph4ai.github.io/graph4nlp/guide/construction/iegraphconstruction.html#merge-strategy).
We recommend this settings:
- edge_strategy: 'as_node'
- merge_strategy: null

However, since the input text for text classification is not very long, the OpenIE provided by Stanford CoreNLP does not always extract the triples, which leads to the inability to construct the corresponding IE graph. In summary, the ``IEBasedGraphConstruction`` provided in our ``graph4nlp`` library is not well suited for text classification tasks. You can try it in summarization task or customize the IE graph construction according to your target task.

**Comment by liuchenzhengyi** [comment]
I see. Thank you!
